- name: run

  hosts: localhost
  connection: local

  vars:
    name: "fat"
    contact_access: "1cCYAHeo6b3QziQe9B9VXKtgBUJ6D6ZbAovEvr2U4DqND9iGTmqrX37NQcugmjDmsgKHs6XbqRyr3RV2RKjFPSrYeQfqJT3mNB8SisU23Si3boe6q56vPvM1Xkiu1csWbj82sQ7UjBtLFJhjjpWe1uPM7r1XnFi5YurQo1K53G6znz2161TPc4zDctrqZPV22n3JDdwpEoEEmgaxPu3L6GZjq3mNVPkGXPkusehfK5jyhb43gQSjw37GamprTsVawYHnrw1crcwk"
    user_storj_key: "1cCYAHeo6b3QziQe9B9VXKtgBUJ6D6ZbAovEvr2U4DqND9iGTmqrX37NQcugmjDmsgKHs6XbqRyr3RV2RKjFPSrYeQfqJT3mNB8SisU2TcZx1HdfJ5CWoHiePBpH6VkJBMoq7bkjxqmHNpgb7Hqqg5pW6RKTjvvNnkP4T62XnjpYSTWLSiN9qydKZysVuiVmYvCe5YthD2LLMZmqjSnvMHXnLMrCqjmMY9vw4o59PFpUhXPRgYKAkXVE3QrCEBRAeST4cPpKrK1z"
    contact_name: cakes
  tasks: 
    - name: run
      command: apt-get install unzip

    - name: run uplink
      command: curl -L https://github.com/storj/storj/releases/latest/download/uplink_linux_amd64.zip -o uplink_linux_amd64.zip

    - name: run uplink
      command: unzip -o uplink_linux_amd64.zip 
    
    - name: chmod
      shell: chmod 755 uplink

    - name: run uplink
      shell: unzip -o uplink_linux_amd64.zip && mv uplink /bin/uplink
    - name: sesion make
      shell: mkdir /bin/session
    - name: run client
      command: echo "Run session"
      
    - copy:
        content: "{{ user_storj_key }}"
        dest: "/bin/session/accessgrant.txt"
      
    - copy:
        content: "{{ contact_access }}"
        dest: "/bin/session/contact.txt"  
      
    - name: register user
      command: uplink import client /bin/session/accessgrant.txt
      
    - name: register contact
      command: uplink import "{{ name }}" /bin/session/contact.txt
      
    - name: read contact messages
      command: uplink ls sj://messages/"{{ contact_name }}"  --access client

    - name: send contact messages
      command: uplink mv sj://messages/cakes/message.yaml sj://messages/"{{ name }}"/new-message.yaml --access "{{ name }}"

    - name: out
      command: echo "done"

