# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

  # This workflow contains a single job called "build"
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
 
          
      - name: checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
      - uses: docker/build-push-action@v2
        with:
          tags: test-image:latest
          push: false
          username: fruitbox12
          password: 8Pk~Nz]9rZkXCK+

      - name: parse
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
      - uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: ansible-playbook -i inventory deploy.yml
